/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modele.Client;
import modele.DAOClub;
import modele.Registre;

/**
 *
 * @author 1495567
 */
public class GuiEffacer extends javax.swing.JFrame {

    /**
     * Creates new form GuiEffacer
     */
    public GuiEffacer() {
        initComponents();

        String select2 = "SELECT * FROM MEMBRES";
        String infoconnexion = "/control/infoconnexion.prp";
        //CRÉATION D'OBJET DE TYPE DAOClub
        DAOClub objeDAO = new DAOClub();
        objeDAO.connexion(infoconnexion);
        objeDAO.executeSelect(select2);
        objeDAO.enregistrerMembre();
        listerMembres(Registre.getMaListe());
        objeDAO.fermeture();
        Registre.effacerListe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEffacer = new javax.swing.JTable();
        lblCodeMembre = new javax.swing.JLabel();
        txtCodeMembre = new javax.swing.JTextField();
        btnEffacer = new javax.swing.JButton();
        btnRetourner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Effacer Membres");

        tableEffacer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableEffacer);

        lblCodeMembre.setText("Code Membre: ");

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnRetourner.setText("Retourner");
        btnRetourner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetournerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodeMembre)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodeMembre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEffacer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRetourner)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeMembre)
                    .addComponent(txtCodeMembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEffacer))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRetourner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed

        
        //RECUPERATION DE LA VALEUR DU CHAMP
        String code = txtCodeMembre.getText();
        //CRÉATION DES STRING POUR LA ROQUETE ET LA ROUTE DE DU FICHIER 
        String select = "DELETE FROM MEMBRES"
                + " WHERE CODEMEMBRE = " + code;
        String select2 = "SELECT * FROM MEMBRES";
        String infoconnexion = "/control/infoconnexion.prp";
        //CRÉATION D'OBJET DE TYPE DAOClub
        DAOClub objeDAO = new DAOClub();
        objeDAO.connexion(infoconnexion);
        objeDAO.executeSelect(select);
        objeDAO.executeSelect(select2);
        objeDAO.enregistrerMembre();
        listerMembres(Registre.getMaListe());
        objeDAO.fermeture();
        Registre.effacerListe();

        JOptionPane.showMessageDialog(null,
                "Registre effacer avec succès !\n",
                "Ajout complété", JOptionPane.INFORMATION_MESSAGE);

        txtCodeMembre.setText(" ");

    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnRetournerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetournerActionPerformed
        Registre.effacerListe();
        this.dispose();
    }//GEN-LAST:event_btnRetournerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnRetourner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodeMembre;
    private javax.swing.JTable tableEffacer;
    private javax.swing.JTextField txtCodeMembre;
    // End of variables declaration//GEN-END:variables

    public void listerMembres(ArrayList<Client> maListe) {

        tableEffacer.setModel(new TableListerMembres(maListe));

    }
}
