/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import connexion.ConfigDB;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modele.Client;
import modele.DAOClub;
import utils.Utilitaire;

/**
 *
 * @author 1495567
 */
public class GuiInserer extends javax.swing.JFrame {

    /**
     * Creates new form GuiInserer
     */
    public GuiInserer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodeMembre = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        lblStatut = new javax.swing.JLabel();
        lblRevenueAnnuel = new javax.swing.JLabel();
        btnEnregistre = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtStatut = new javax.swing.JTextField();
        txtRevenueAnnuel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insérer Membre");

        lblCodeMembre.setText("Code Membre: ");

        lblNom.setText("Nom: ");

        lblPrenom.setText("Prénom: ");

        lblAdresse.setText("Adresse: ");

        lblStatut.setText("Statut: ");

        lblRevenueAnnuel.setText("Revenue Annuel: ");

        btnEnregistre.setText("Enregistrer");
        btnEnregistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistreActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Retourner");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        txtRevenueAnnuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRevenueAnnuelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRevenueAnnuel)
                            .addComponent(lblStatut)
                            .addComponent(lblAdresse)
                            .addComponent(lblPrenom)
                            .addComponent(lblCodeMembre)
                            .addComponent(lblNom))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE))
                            .addComponent(txtNom)
                            .addComponent(txtPrenom)
                            .addComponent(txtAdresse)
                            .addComponent(txtStatut)
                            .addComponent(txtRevenueAnnuel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEnregistre)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnnuler)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeMembre)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrenom)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdresse)
                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatut)
                    .addComponent(txtStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRevenueAnnuel)
                    .addComponent(txtRevenueAnnuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnregistre)
                    .addComponent(btnAnnuler))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRevenueAnnuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRevenueAnnuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRevenueAnnuelActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnEnregistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistreActionPerformed

        //DÉCLARATION D'OBJET 
        DAOClub objeDAO = new DAOClub();
        //CRÉATION D'UN STRING AVEC LA RÊQUETE POUR INSÉRER LES DONNÉES
        String requete = "INSERT INTO membres VALUES (?,?,?,?,?,?)";
        //CRÉATION D'UN STRING POUR LA ROUTE DU FICHIER DE CONNEXION
        String infoconnexion = "/control/infoconnexion.prp";
        try {
            //validation champs vide
            if ((Utilitaire.validerChampsVide(txtCode) == false) && (Utilitaire.validerChampsVide(txtNom) == false)
                    && (Utilitaire.validerChampsVide(txtPrenom) == false) && (Utilitaire.validerChampsVide(txtAdresse) == false)
                    && (Utilitaire.validerChampsVide(txtStatut) == false) && (Utilitaire.validerChampsVide(txtRevenueAnnuel) == false)) {

                if (Utilitaire.validerChampRevenue(txtRevenueAnnuel)) {
                    //RÉCUPERER L'INFORMATION DES CHAMPS
                    Integer codeMembre = Integer.parseInt(txtCode.getText());
                    String nom = txtNom.getText();
                    String prenom = txtPrenom.getText();
                    String adresse = txtAdresse.getText();
                    String statut = txtStatut.getText();
                    Double revenueAnnuel = Double.parseDouble(txtRevenueAnnuel.getText());
                    //ENVOI DU STRING infoconnexion AU MÉTHODE CONNEXION
                    objeDAO.connexion(infoconnexion);
                    //ENVOI DES VARIABLES ET DU STRING requete AU MÉTHODE ExecuteSQL
                    objeDAO.ExecuteSQL(requete, codeMembre, nom, prenom, adresse, statut, revenueAnnuel);
                    //FERMETURE DE LA CONNEXION
                    objeDAO.fermeture();

                    JOptionPane.showMessageDialog(null,
                            "Registre ajouté avec succès !\n",
                            "Ajout complété", JOptionPane.INFORMATION_MESSAGE);

                    txtCode.setText("0");
                    txtNom.setText(" ");
                    txtPrenom.setText(" ");
                    txtAdresse.setText(" ");
                    txtStatut.setText(" ");
                    txtRevenueAnnuel.setText("0");

                } else {

                    JOptionPane.showMessageDialog(null,
                            "Erreur: " + "La revenue annuelle doit être égale ou supérieur à 0",
                            "Alerte:", JOptionPane.ERROR_MESSAGE);
                }

            } else {

                JOptionPane.showMessageDialog(null,
                        "Erreur: " + "Tous les champs doivent être remplir",
                        "Alerte:", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                    "Erreur: " + "Les champs code et revenue annuel doivent être numérique",
                    "Alerte:", JOptionPane.ERROR_MESSAGE);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Erreur: " + "Le resgistre existe déjà dans la base de données",
                    "Alerte:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnregistreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnregistre;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblCodeMembre;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblRevenueAnnuel;
    private javax.swing.JLabel lblStatut;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtRevenueAnnuel;
    private javax.swing.JTextField txtStatut;
    // End of variables declaration//GEN-END:variables
}
