/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import modele.Client;
import modele.DAOClub;
import modele.Registre;

/**
 *
 * @author 1495567
 */
public class GuiListerStatut extends javax.swing.JFrame {

    /**
     * Creates new form GuiListerStatut
     */
    public GuiListerStatut() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMembresStatut = new javax.swing.JTable();
        lblStatut = new javax.swing.JLabel();
        txtStatut = new javax.swing.JTextField();
        btnLister = new javax.swing.JButton();
        btnRetourner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liste des Membres par Statut");

        tableMembresStatut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableMembresStatut);

        lblStatut.setText("Statut: ");

        txtStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatutActionPerformed(evt);
            }
        });

        btnLister.setText("Lister");
        btnLister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListerActionPerformed(evt);
            }
        });

        btnRetourner.setText("Retourner");
        btnRetourner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetournerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatut)
                        .addGap(18, 18, 18)
                        .addComponent(txtStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLister)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRetourner)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatut)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLister)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRetourner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatutActionPerformed

    private void btnListerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListerActionPerformed
        //CRÉATION DES STRING POUR LA ROQUETE ET LA ROUTE DE DU FICHIER 
        String infoconnexion = "/control/infoconnexion.prp";
        //CRÉATION D'OBJET DE TYPE DAOClub
        DAOClub objeDAO = new DAOClub();
        //RECUPERATION DE LA VALEUR DU CHAMP
        String statut = txtStatut.getText();
        String select = ("SELECT * FROM MEMBRES"
                + " WHERE STATUT = '" + statut + "'");
        objeDAO.connexion(infoconnexion);
        objeDAO.executeSelect(select);
        objeDAO.enregistrerMembre();
        listerMembres(Registre.getMaListe());
        objeDAO.fermeture();
        Registre.effacerListe();

    }//GEN-LAST:event_btnListerActionPerformed

    private void btnRetournerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetournerActionPerformed
        Registre.effacerListe();
        this.dispose();
    }//GEN-LAST:event_btnRetournerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLister;
    private javax.swing.JButton btnRetourner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatut;
    private javax.swing.JTable tableMembresStatut;
    private javax.swing.JTextField txtStatut;
    // End of variables declaration//GEN-END:variables

    public void listerMembres(ArrayList<Client> maListe) {

        tableMembresStatut.setModel(new TableListerMembres(maListe));

    }
}
