/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import modele.Client;
import modele.DAOClub;
import modele.Registre;

/**
 *
 * @author 1495567
 */
public class GuiPrincipal extends javax.swing.JFrame {

    //ArrayList<Client> liste = new ArrayList<Client>();
    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserer = new javax.swing.JButton();
        btnAffichageMembres = new javax.swing.JButton();
        btnAffichageStatut = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnSoritr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Club des Fleuristes");

        btnInserer.setText("INSÉRER MEMBRE");
        btnInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsererActionPerformed(evt);
            }
        });

        btnAffichageMembres.setText("AFFICHAGE MEMBRES");
        btnAffichageMembres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAffichageMembresActionPerformed(evt);
            }
        });

        btnAffichageStatut.setText("AFFICHAGE PAR STATUT");
        btnAffichageStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAffichageStatutActionPerformed(evt);
            }
        });

        btnSupprimer.setText("SUPPRIMER");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnSoritr.setText("SORTIR");
        btnSoritr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoritrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSoritr, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAffichageStatut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAffichageMembres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnInserer)
                .addGap(30, 30, 30)
                .addComponent(btnAffichageMembres)
                .addGap(28, 28, 28)
                .addComponent(btnAffichageStatut)
                .addGap(30, 30, 30)
                .addComponent(btnSupprimer)
                .addGap(30, 30, 30)
                .addComponent(btnSoritr)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsererActionPerformed
        GuiInserer objeInserer = new GuiInserer();
        objeInserer.setVisible(true);
    }//GEN-LAST:event_btnInsererActionPerformed

    private void btnSoritrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoritrActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSoritrActionPerformed

    private void btnAffichageMembresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAffichageMembresActionPerformed

        GuiListerMembres objeListerM = new GuiListerMembres();
        objeListerM.setVisible(true);

    }//GEN-LAST:event_btnAffichageMembresActionPerformed

    private void btnAffichageStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAffichageStatutActionPerformed

        GuiListerStatut objeListerM = new GuiListerStatut();
        objeListerM.setVisible(true);

    }//GEN-LAST:event_btnAffichageStatutActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed

        GuiEffacer objEffacer = new GuiEffacer();
        objEffacer.setVisible(true);
    }//GEN-LAST:event_btnSupprimerActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAffichageMembres;
    private javax.swing.JButton btnAffichageStatut;
    private javax.swing.JButton btnInserer;
    private javax.swing.JButton btnSoritr;
    private javax.swing.JButton btnSupprimer;
    // End of variables declaration//GEN-END:variables

}
